[model_arguments]
v2 = false
v_parameterization = false
pretrained_model_name_or_path = "/appdata/finetuning/sd-models/majicmixRealistic_v6.safetensors"

[dataset_arguments]
train_data_dir = "/appdata/finetuning/train/zjz_blue/v3"
reg_data_dir = ""
resolution = "576,768"
prior_loss_weight = 1

[additional_network_arguments]
network_dim = 128
network_alpha = 128
network_train_unet_only = false
network_train_text_encoder_only = false
network_module = "networks.lora"
network_args = []

[optimizer_arguments]
unet_lr = 1e-4
text_encoder_lr = 1e-5

optimizer_type = "AdamW8bit"
lr_scheduler = "cosine_with_restarts"
lr_warmup_steps = 0
lr_restart_cycles = 1

[training_arguments]
train_batch_size = 2
noise_offset = 0.0
keep_tokens = 1
min_bucket_reso = 256
max_bucket_reso = 1024
caption_extension = ".txt"
max_token_length = 225
seed = 1337
xformers = true
lowram = false
max_train_epochs = 15
resolution = "576,768"
clip_skip = 2
mixed_precision = "fp16"

[sample_prompt_arguments]
sample_sampler = "euler"
sample_every_n_epochs = 2

[saving_arguments]
output_name = "zjz_blue_majic_576_768_v13"
save_every_n_epochs = 2
save_state = false
save_model_as = "safetensors"
output_dir = "/appdata/finetuning/output/zjz_blue/lora_v13"
logging_dir = "./logs/zjz_blue/lora_v13"
log_prefix = ""
save_precision = "fp16"

[others]
cache_latents = true
shuffle_caption = true
enable_bucket = true
#scale_weight_norms = 10.0