[model_arguments]
v2 = false
v_parameterization = false
pretrained_model_name_or_path = "/appdata/finetuning/sd-models/yqAvatar_ft_512_512_v40.safetensors"

[dataset_arguments]
train_data_dir = "/appdata/finetuning/train/my_test11/512x512/v1"
reg_data_dir = ""
resolution = "512,512"
prior_loss_weight = 1

[additional_network_arguments]
network_dim = 64
network_alpha = 48
network_train_unet_only = false
network_train_text_encoder_only = false
network_module = "networks.lora"
network_args = []

[optimizer_arguments]
unet_lr = 0.0001
text_encoder_lr = 0.00001

optimizer_type = "AdamW8bit"
lr_scheduler = "cosine_with_restarts"
lr_warmup_steps = 0
lr_restart_cycles = 1

[training_arguments]
train_batch_size = 4
noise_offset = 0.0
keep_tokens = 1
min_bucket_reso = 256
max_bucket_reso = 1024
caption_extension = ".txt"
max_token_length = 225
seed = 1337
xformers = true
lowram = false
max_train_epochs = 10
resolution = "512,512"
clip_skip = 2
mixed_precision = "fp16"

[sample_prompt_arguments]
sample_sampler = "euler"
sample_every_n_epochs = 1

[saving_arguments]
output_name = "my_test11_512_512_v5"
save_every_n_epochs = 1
save_state = false
save_model_as = "safetensors"
output_dir = "/appdata/finetuning/output/my_test11/lora_v5"
logging_dir = "./logs/my_test11/lora_v5"
log_prefix = ""
save_precision = "fp16"

[others]
cache_latents = true
shuffle_caption = false
enable_bucket = true
scale_weight_norms = 1.0